#!/bin/sh
. "$(dirname -- "$0")/_/husky.sh"
exec < /dev/tty
git stash push -k --quiet -u
docker-compose run --rm showed bash -c "npm --no-update-notifier run test && npx --no-update-notifier tsc --noEmit && npx --no-update-notifier eslint" > /dev/tty
git stash pop --quiet && exit 0
